var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/0knu_next_dist_esm_0jtoisr._.js")
R.c("server/chunks/ssr/[root-of-the-server]__092x1s5._.js")
R.c("server/chunks/ssr/0knu_next_dist_esm_0wd8vua._.js")
R.c("server/chunks/ssr/0knu_next_dist_compiled_05h1e4p._.js")
R.c("server/chunks/ssr/0knu_next_dist_server_route-modules_app-page_00y96z1._.js")
R.c("server/chunks/ssr/[externals]__0n13xf4._.js")
R.c("server/chunks/ssr/Desktop_HI-Sing_0ew4wi3._.js")
R.c("server/chunks/ssr/0knu_next_dist_client_components_138dxpj._.js")
R.c("server/chunks/ssr/0knu_next_dist_client_components_builtin_forbidden_0a5oatq.js")
R.c("server/chunks/ssr/0knu_next_dist_client_components_builtin_unauthorized_0udb1gm.js")
R.c("server/chunks/ssr/0knu_next_dist_client_components_builtin_global-error_03yj981.js")
R.c("server/chunks/ssr/Desktop_HI-Sing__next-internal_server_app_page_actions_0gjlfil.js")
R.m("[project]/Desktop/HI-Sing/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { MODULE_0 => \"[project]/Desktop/HI-Sing/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_1 => \"[project]/Desktop/HI-Sing/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/Desktop/HI-Sing/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/Desktop/HI-Sing/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/Desktop/HI-Sing/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/Desktop/HI-Sing/src/app/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)")
module.exports=R.m("[project]/Desktop/HI-Sing/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { MODULE_0 => \"[project]/Desktop/HI-Sing/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_1 => \"[project]/Desktop/HI-Sing/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/Desktop/HI-Sing/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/Desktop/HI-Sing/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/Desktop/HI-Sing/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/Desktop/HI-Sing/src/app/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)").exports
