var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0e4cdoo._.js")
R.c("server/chunks/ssr/0knu_next_dist_esm_build_templates_app-page_0xvbw1s.js")
R.c("server/chunks/ssr/[root-of-the-server]__0e4zy~s._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0gc-4uk._.js")
R.c("server/chunks/ssr/Desktop_HI-Sing_src_app_layout_tsx_01-nat8._.js")
R.c("server/chunks/ssr/0knu_next_dist_client_components_138dxpj._.js")
R.c("server/chunks/ssr/0knu_next_dist_client_components_builtin_forbidden_0a5oatq.js")
R.c("server/chunks/ssr/0knu_next_dist_client_components_builtin_unauthorized_0udb1gm.js")
R.c("server/chunks/ssr/0knu_next_dist_client_components_builtin_global-error_03yj981.js")
R.c("server/chunks/ssr/Desktop_HI-Sing__next-internal_server_app_page_actions_0gjlfil.js")
R.m(79996)
module.exports=R.m(79996).exports
